name: Build project
on: [push, pull_request]
jobs:
  build-jdk8-zulu:
    runs-on: ubuntu-latest
    name: Build with Java 8 - Zulu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk8-zulu-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk8-zulu-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 1.8
      - name: Maven verify
        run: mvn -B verify
      - name: Maven Javadoc
        run: mvn javadoc:javadoc
  build-jdk11-zulu:
    runs-on: ubuntu-latest
    name: Build with Java 11 - Zulu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk11-zulu-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk11-zulu-
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
      - name: Maven verify
        run: mvn -B verify
  build-jdk21-temurin:
    runs-on: ubuntu-latest
    name: Build with Java 21 - Temurin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk21-temurin-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk21-temurin-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Maven verify
        run: mvn -B verify
  build-jdk21-zulu:
    runs-on: ubuntu-latest
    name: Build with Java 21 - Zulu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk21-zulu-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk21-zulu-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Maven verify
        run: mvn -B verify
  build-jdk21-microsoft:
    runs-on: ubuntu-latest
    name: Build with Java 21 - Microsoft
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk21-ms-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk21-ms-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 11
      - name: Maven verify
        run: mvn -B verify
